---

- name: Deploy infra
  hosts: localhost
  tasks:
    - name: Create infrastrure on AWS
      import_role:
        name: create_infra
      tags:
        - install
        - deploy
        - jenkins
        - xebenvs

- name: Deploy Jenkins
  hosts: jenkins
  gather_facts: no
  tasks:
    - name: Wait 600 seconds for jenkins connection to become reachable/usable
      wait_for_connection:
    - name: Install python
      import_role:
        name: python_install
      tags:
        - install
    - name: Install docker
      import_role:
        name: docker_install
      tags:
        - install
    - name: Deploy Jenkins
      import_role:
        name: jenkins_deploy
      tags:
        - install
        - deploy
  tags:
    - jenkins
  become: yes

- name: Deploy Xebenvs
  hosts: environments
  tasks:
    - name: Wait 600 seconds for the env connection to become reachable/usable
      wait_for_connection:
    - name: Install python
      import_role:
        name: python_install
      tags:
        - install
    - name: Install docker
      import_role:
        name: docker_install
      tags:
        - install
    - name: Deploy xebenvs
      import_role:
        name: xebenv_deploy
      tags:
        - install
        - deploy
  tags:
    - xebenvs
  become: yes

