---

- name: Ensure needed params were set
  import_role:
    name: check_params
  vars:
    params: "{{ needed_params }}"

- name: Generate the jenkins' confs
  import_tasks: generate_confs.yml

- name: Create docker directories
  file:
    path: "{{ path_to_volume }}"
    state: directory
  become: yes

- name: Tear down existing services
  docker_compose:
    project_src: "{{ path_to_installer }}"
    state: absent

- name: Create and start services
  docker_compose:
    project_src: "{{ path_to_installer }}"
    build: yes
  register: output

- name: Wait for Jenkins installation to finish
  uri:
    url: "{{ jenkins_url }}/login?from=%2F"
    method: GET
    status_code: 200
  register: answer
  until: answer.status == 200
  retries: 60
  delay: 4
