---

- name: Generate the jenkins' confs
  import_tasks: generate_confs.yml

- name: Create docker directories
  file:
    path: "{{ path_to_volume }}"
    state: directory
  become: yes

- name: Tear down existing services
  docker_compose:
    project_src: "{{ path_to_installer }}"
    state: absent
   
- name: Create and start services
  docker_compose:
    project_src: "{{ path_to_installer }}"
    build: yes
  register: output

- name: Wait for Jenkins installation to finish
  uri: 
    url: "{{ jenkins_url }}/login?from=%2F"
    method: GET
    status_code: 200
  register: answer
  until: answer.status == 200
  retries: 60
  delay: 4

- name: Backup jenkins.yml
  delegate_to: "{{ groups['jenkins'][0] }}"
  copy:
    src: "{{ jenkins_ref_dir }}/jenkins.yml"
    dest: "{{ jenkins_ref_dir }}/jenkins.yml.bkp"
    remote_src: yes

- name: Remove jenkins.yml content
  delegate_to: "{{ groups['jenkins'][0] }}"
  copy:
    content: ""
    dest: "{{ jenkins_ref_dir }}/jenkins.yml"

- name: Creating virtual environment for ansible execution
  delegate_to: "{{ groups['jenkins'][0] }}"
  pip:
    requirements: "{{ jenkins_ref_dir }}/requirements.txt"
    virtualenv: "{{ jenkins_venv_dir }}"
    virtualenv_python: python
