---

- name: Ensure ssh dir exists
  file:
    path: ~/.ssh
    state: directory
    mode: "700"
  delegate_to: "{{ groups['jenkins'][0] }}"

- name: Generate ssh key on Jenkins
  openssh_keypair:
    path: ~/.ssh/{{ ssh_key_name }}
  delegate_to: "{{ groups['jenkins'][0] }}"
  register: pub

- name: Authorize key in backs
  authorized_key:
    user: "{{ jenkins_to_back_user }}"
    state: present
    key: "{{ pub.public_key }}"
  delegate_to: "{{ item }}"
  loop: "{{ groups['back'] }}"
